name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          composer install --no-dev --optimize-autoloader

      - name: Deploy to staging server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          source: ./
          target: /var/www/inceptive/

  deploy_production:
    needs: [deploy_staging]
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
        id: approval
        run: echo "Approve deployment to production"

      - name: Check Manual Approval
        run: |
          if [ "${{ steps.approval.outputs.result }}" != "Approve deployment to production" ]; then
            echo "Deployment to production not approved, exiting."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          composer install --no-dev --optimize-autoloader

      - name: Deploy to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: /var/www/inceptive/
